import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import fs from 'fs/promises';
import path from 'path';
import os from 'os';

// mock AI SDK —— 工厂函数内不能引用外部变量
vi.mock('@anthropic-ai/claude-agent-sdk', () => ({
  query: vi.fn(({ options }) => {
    const projectDir = options.cwd;
    const harnessDir = path.join(projectDir, '.harness');

    // 使用同步 fs 在工厂内创建文件
    const fsSync = require('fs');
    fsSync.mkdirSync(harnessDir, { recursive: true });
    fsSync.writeFileSync(
      path.join(harnessDir, 'spec.md'),
      '# Test Specification\n\nThis is a test spec generated by mock AI.',
      'utf-8'
    );
    fsSync.writeFileSync(
      path.join(harnessDir, 'tasks.json'),
      JSON.stringify({
        project: {
          name: 'test-project',
          version: '1.0.0',
          created_at: new Date().toISOString(),
        },
        tasks: [
          {
            id: 'task-1',
            title: 'Implement core feature',
            status: 'pending',
            description: 'Implement the core feature of the application',
            dependencies: [],
            attempts: 0,
          },
        ],
        statistics: {
          total: 1,
          pending: 1,
          in_progress: 0,
          completed: 0,
          blocked: 0,
          needs_human: 0,
        },
      }, null, 2),
      'utf-8'
    );

    // 返回 AsyncGenerator，yield success 消息
    return (async function* () {
      yield {
        type: 'result',
        subtype: 'success',
        usage: { input_tokens: 100, output_tokens: 200 },
      };
    })();
  }),
}));

// mock child_process
vi.mock('child_process', () => ({
  exec: vi.fn((cmd: string, opts: any, cb: any) => {
    if (cb) cb(null, { stdout: '', stderr: '' });
    return { stdout: '', stderr: '' };
  }),
}));

vi.mock('util', () => ({
  promisify: vi.fn(() => vi.fn().mockResolvedValue({ stdout: '', stderr: '' })),
}));

const exitSpy = vi.spyOn(process, 'exit').mockImplementation((() => {}) as any);
const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {});
const errorSpy = vi.spyOn(console, 'error').mockImplementation(() => {});

import { initCommand } from '../../src/commands/init.js';

describe('initCommand simple mode E2E', () => {
  let tempDir: string;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'init-e2e-'));
    exitSpy.mockClear();
    logSpy.mockClear();
    errorSpy.mockClear();
  });

  afterEach(async () => {
    await fs.rm(tempDir, { recursive: true, force: true });
  });

  it('should initialize project with --text option', async () => {
    const projectDir = path.join(tempDir, 'my-app');

    await initCommand(projectDir, {
      mode: 'simple',
      text: '做一个计算器应用',
      name: 'calculator',
    });

    // 验证目录结构
    const harnessDir = path.join(projectDir, '.harness');
    const harnessStat = await fs.stat(harnessDir);
    expect(harnessStat.isDirectory()).toBe(true);

    // 验证 tasks.json 存在且格式正确
    const tasksPath = path.join(harnessDir, 'tasks.json');
    const tasksContent = await fs.readFile(tasksPath, 'utf-8');
    const tasks = JSON.parse(tasksContent);
    expect(tasks.project).toBeDefined();
    expect(tasks.tasks).toBeInstanceOf(Array);
    expect(tasks.statistics).toBeDefined();

    // 验证 spec.md 存在
    const specPath = path.join(harnessDir, 'spec.md');
    const specContent = await fs.readFile(specPath, 'utf-8');
    expect(specContent).toContain('Test Specification');

    // 验证 console 输出
    expect(logSpy).toHaveBeenCalledWith(expect.stringContaining('初始化完成'));
    expect(logSpy).toHaveBeenCalledWith(expect.stringContaining('下一步'));
  });

  it('should initialize project with --prd option', async () => {
    const projectDir = path.join(tempDir, 'my-app-prd');
    const prdPath = path.join(tempDir, 'test-prd.md');
    await fs.writeFile(prdPath, '# Product Requirements\n\n这是一个测试 PRD 文档。', 'utf-8');

    await initCommand(projectDir, {
      mode: 'simple',
      prd: prdPath,
      name: 'prd-app',
    });

    // 验证 tasks.json 和 spec.md 创建
    const harnessDir = path.join(projectDir, '.harness');
    const tasksPath = path.join(harnessDir, 'tasks.json');
    const specPath = path.join(harnessDir, 'spec.md');

    await expect(fs.access(tasksPath)).resolves.toBeUndefined();
    await expect(fs.access(specPath)).resolves.toBeUndefined();

    // 验证读取了 PRD 文件
    expect(logSpy).toHaveBeenCalledWith(expect.stringContaining('读取 PRD'));
  });

  it('should exit when simple mode lacks text/prd/json', async () => {
    const projectDir = path.join(tempDir, 'no-input');

    await initCommand(projectDir, {
      mode: 'simple',
      name: 'no-input-app',
    });

    expect(errorSpy).toHaveBeenCalledWith(expect.stringContaining('必须提供'));
    expect(exitSpy).toHaveBeenCalledWith(1);
  });

  it('should handle existing project directory', async () => {
    const projectDir = path.join(tempDir, 'existing-dir');
    await fs.mkdir(projectDir, { recursive: true });
    // 预先创建一些文件
    await fs.writeFile(path.join(projectDir, 'README.md'), '# Existing', 'utf-8');

    await initCommand(projectDir, {
      mode: 'simple',
      text: 'Test project',
      name: 'existing',
    });

    // 验证原有文件还在
    const readmeContent = await fs.readFile(path.join(projectDir, 'README.md'), 'utf-8');
    expect(readmeContent).toBe('# Existing');

    // 验证 .harness 目录被创建
    const harnessDir = path.join(projectDir, '.harness');
    await expect(fs.access(harnessDir)).resolves.toBeUndefined();
  });

  it('should skip git init when already initialized', async () => {
    const projectDir = path.join(tempDir, 'has-git');
    await fs.mkdir(projectDir, { recursive: true });
    await fs.mkdir(path.join(projectDir, '.git'), { recursive: true });

    await initCommand(projectDir, {
      mode: 'simple',
      text: 'Test with git',
      name: 'git-app',
    });

    // 验证输出包含跳过信息
    expect(logSpy).toHaveBeenCalledWith(expect.stringContaining('Git'));

    // 验证初始化仍然完成
    const harnessDir = path.join(projectDir, '.harness');
    await expect(fs.access(harnessDir)).resolves.toBeUndefined();
  });

  it('should print correct next steps for simple mode', async () => {
    const projectDir = path.join(tempDir, 'next-steps');

    await initCommand(projectDir, {
      mode: 'simple',
      text: 'Test next steps',
      name: 'steps-app',
    });

    // 验证输出了下一步提示
    expect(logSpy).toHaveBeenCalledWith(expect.stringContaining('下一步'));
    expect(logSpy).toHaveBeenCalledWith(expect.stringContaining('spec.md'));
    expect(logSpy).toHaveBeenCalledWith(expect.stringContaining('tasks.json'));
    expect(logSpy).toHaveBeenCalledWith(expect.stringContaining('autorun-harness run'));
  });
});
